### ISSUE TITLE
AppImage cannot run on Ubuntu bionic

### ISSUE THREAD

**Issue by probonopd** [sourcebox/sysex-drop#1]
This was built on a too new system and hence cannot run on all still-supported Ubuntu releases:

```
AppRun: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/2654

**Comment by sourcebox** [comment]
@probonopd Please have a look at the `0.1.0-beta2` release. It was build via GitHub CI using the ubuntu-18.04 image.

**Comment by probonopd** [comment]
Thank you very much @sourcebox. It starts to run now (but the automated [test](https://github.com/AppImage/appimage.github.io/pull/2654#issuecomment-917369309) cannot take a screenshot, which may well be caused by the fact that the server running the [test script](https://github.com/AppImage/appimage.github.io/blob/master/code/worker.sh) is headless). Optimistic that it will run just fine on a real machine now. Thanks!
