### ISSUE TITLE
Windows 7, 8 and 10 needs apps to be DPI-aware

### ISSUE THREAD

**Issue by BenMcLean** [sourcebox/sysex-drop#2]
When I started the app, the "Start" button wasn't visible. I think this is because I run Windows with high DPI for my low vision. I managed to make it appear by changing the "High DPI Settings" in Windows to make the System scale the app. But I shouldn't have to do this, because DPI-awareness is a requirement for Windows apps to work right.

Some background on this issue:
On Windows 10, there is a feature called UI Scaling described in this article: https://www.thurrott.com/windows/windows-10/4597/windows-10-feature-focus-display-scaling

This is a good feature for people with vision problems to make the text and GUI elements bigger in most Windows programs.

This feature first started on Windows XP but programmers only started having to worry about it when Windows 7 started trying to scale up apps that didn't tell the newer Windows API that they were DPI-aware. As InfoWorld says, "For apps that aren't high-DPI aware, Microsoft has a quick and dirty fix called DPI virtualization. Windows deliberately reports the wrong DPI resolution to such apps, so their elements render as if they were on a lower-resolution display. The results are then zoomed to fit the current display." http://www.infoworld.com/article/2952506/microsoft-windows/high-resolution-displays-reveal-windows-10-blind-spot.html

What needs to be done to fix this is to make Windows builds DPI-aware, as discussed in this article from Microsoft https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx and explained in this tutorial. https://msdn.microsoft.com/en-us/library/windows/desktop/dd464659(v=vs.85).aspx

Here is a really good blog post about the issue: http://www.hanselman.com/blog/LivingAHighDPIDesktopLifestyleCanBePainful.aspx

**Comment by sourcebox** [comment]
I'm not sure if this is something I can fix myself but has to be done in the underlying GUI framework I use for this app. I'm gonna drop a note to the devs of this library for some advice.

**Comment by sourcebox** [comment]
@BenMcLean: I'm currently doing some investigation on this. Is it possible for you to attach a screenshot? I have some assumption what could be the cause.

**Comment by BenMcLean** [comment]
Will try to get you a screenshot later.

**Comment by sourcebox** [comment]
@BenMcLean: I created a new build that includes some fixes. You can download it in the *Actions* section. Please give it a try.

**Comment by BenMcLean** [comment]
> I created a new build that includes some fixes. You can download it in the _Actions_ section. Please give it a try.

This new build appears to fix the issue on my PC. Thanks! 👍
